<?php
/**
 * Create By Kamon
 * User: Kamon
 * Date: {2021/2/1}
 * Time: {22:20}
 */
namespace app\admin\controller;

use app\BaseController;
use think\exception\HttpResponseException;

class AdminBase extends BaseController {

    public $user = null;

    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub

        //判断是否登录， 采用中间件形式
//        if($this->isLogin() == false){
//            return $this->redirect('/admin/login/index', 302);
//        }
    }


    /**
     * 判断是否登录
     * @return bool
     */
    public function isLogin() {
        $this->user = session(config("admin.session_admin"));
        if(empty($this->user)){
            return false;
        }
        return true;
    }

    public function redirect(...$args){
        throw new HttpResponseException(redirect(...$args));
    }
}